kind: environment
environment_name: vido-test
state: active
owner_email: johnathan.v@quali.com
blueprint:
  name: hello-pre-scripts
  repository_name: bps
  commit: 83bb330
inputs:
  agent: vido-prod
tags: {}
grains: {}
