spec_version: 2
description: deploy azure vm

inputs:
  agent:
    type: agent
  public_ip:
    type: string
  user:
    type: string
    default: adminuser
  password:
    type: string
    
grains:
  configure:
    kind: ansible
    depends-on: vm
    spec:
      source:
        store: bps
        path: ansible/configure-win-vm/configure-win-vm.yaml
      agent:
        name: '{{ .inputs.agent }}'
      inventory-file:
        all:
          hosts:
            vm:
              ansible_host: '{{ .inputs.public_ip }}'
              ansible_user: '{{ .inputs.user }}'
              ansible_password: '{{ .inputs.password }}'
              # ansible_become: yes
              # ansible_become_method: sudo
              # ansible_become_pass: '{{ .inputs.password }}' 
              ansible_connection: winrm
              ansible_winrm_transport: ntlm
            localhost:
              ansible_connection: local
